2024-12-25 17:05:19,782 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\osa90\PycharmProjects\modul_12\tests_12_4.py", line 70, in test_run
    object2 = Runner(123)
              ^^^^^^^^^^^
  File "C:\Users\osa90\PycharmProjects\modul_12\tests_12_4.py", line 11, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-25 17:05:19,782 | WARNING | Неверная скорость для объекта Runner
Traceback (most recent call last):
  File "C:\Users\osa90\PycharmProjects\modul_12\tests_12_4.py", line 59, in test_walk
    object1 = Runner('ex',-5)
              ^^^^^^^^^^^^^^^
  File "C:\Users\osa90\PycharmProjects\modul_12\tests_12_4.py", line 16, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
